stages:
  - publish

publish:
  stage: publish
  tags:
    - moreillon
  script:
    # Install dependencies and build app
    - npm install
    - npm run build
    # Bump version (DOES NOT WORK)
    #- npm --no-git-tag-version version patch
    # Auth and publish to NPM
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
